### ISSUE TITLE
Feature request: please provide a method or param which allows to change the business-partner programatically

### ISSUE THREAD

**Issue by spaudanjo** [zalando-incubator/solution-center-navigation#208]
Background: Some apps have the business partner as part of their deep links and would like to change the currently selected business partner depending on that. 
E.g. a method like the former setMerchantById() woulde be nice.

**Comment by cjhowald** [comment]
Per our discussions, the current plan is to introduce a new component parameter. Setting this parameter will update the current business partner and take the same actions as when a user changes it via the BP selector (i.e. update the navigation, get a new access token, emit the changed event). This way, you don't have to duplicate the efforts of the navigation, and we don't risk falling out of sync.

You will be able to set the parameter in your template like so:
```html
<sc-navigation
  ...
  business-partner-id='skdfhjk'
/>
```

Note on business partner names vs IDs: since your application has a name but we require an ID (the name might not be unique), you will have to map the business partner name to an ID. You can do this by calling [our API](https://us-integration.norris.zalan.do/docs/swagger-ui/index.html?url=/docs/swagger.json#!/User/getUserBusinessPartners) to load business partners for a user, providing a [session token](https://github.com/zalando-incubator/solution-center-login/blob/master/src/authentication-service.js#L127) in the Authentication header.
