### ISSUE TITLE
Investigate possible bug in user management link

### ISSUE THREAD

**Issue by dami-gg** [zalando-incubator/solution-center-navigation#236]
I suspect that it's not working properly when showing it only if the user has access to it, since to check this condition we loop all over the accessibleProducts stored in the redux store, and if I'm not wrong these are loaded using the visible=true filter and hence not including the users application, hence it won't ever be found and shown.

Please investigate if I'm right and find another way to handle it

**Comment by dami-gg** [comment]
@frontendherodk I found out a better solution for this. The user object includes the applications so you only need to check for users there

**Comment by frontendherodk** [comment]
Yeah I thought about that already and we also discussed this yesterday with the backend and @cjhowald. The thing is that it's easy to manipulate the object which in itself is not a big deal since it will validate when you try to access user management. It's always a balance. How much effort should you do in the frontend when you have the endpoint for it.
