### ISSUE TITLE
Business Partner menu should close when clicking outside

### ISSUE THREAD

**Issue by frontendherodk** [zalando-incubator/solution-center-navigation#257]

**Comment by dami-gg** [comment]
It's working fine in general but only failing in Insights due to the fact that the content is an iframe loading data from an external URL where event handling is disabled because of cross domain policy...

I'll try to find a way to fix it but if it turns out to be too hacky we should decided whether it's right to do it or not

**Comment by dami-gg** [comment]
It can't be fixed in any way. Showing the whole content of a page based in an iframe had to have some drawbacks... this is the first one we find, let's see what else follows ;)
